gui:
  theme:
    activeBorderColor:
      - "#80d4d5"
      - bold
    inactiveBorderColor:
      - "#b0cccb"
    searchingActiveBorderColor:
      - "#b3c8e9"
      - bold
    optionsTextColor:
      - "#bec8c8"
    selectedLineBgColor:
      - "#bec8c8"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#bec8c8"
    cherryPickedCommitBgColor:
      - "#b3c8e9"
    markedBaseCommitFgColor:
      - "#b3c8e9"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#dde4e3"
